# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
image: rashair/dotnet-node-sdk

definitions:
  caches:
    react-client: GameMaster/ClientApp/node_modules
  steps:
    - step: &Build-and-test
        name: Build and test solution
        caches:
            - dotnetcore
            - react-client
        script:
            - tools/build_and_test.sh
        artifacts:
            - GameMaster/**
            - CommunicationServer/**
            - Player/**
            - Shared/**
    - step: &Run-integration-tests-manual
        name: Run integration tests
        caches:
            - dotnetcore
        trigger: manual
        script:
            - tools/integration-tests.sh
    - step: &Run-integration-tests-auto
        name: Run integration tests
        caches:
            - dotnetcore
        script:
            - tools/integration-tests.sh
pipelines:
    branches:
      master:
        - step: *Build-and-test
        - step: *Run-integration-tests-auto
      develop:
        - step: *Build-and-test
        - step: *Run-integration-tests-manual
