# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
image: atsquad/netcore-nodejs-aws-build-server:2.1.15-v1

definitions:
  steps:
    - step: &Build-and-test
        name: Build and test solution
        caches:
              - dotnetcore
              - node
        script:
          - dotnet restore
          - dotnet build --no-restore $SOLUTION_NAME
          - dotnet test --no-build --no-restore $SOLUTION_NAME
pipelines:
    branches:
      master:
        - step: *Build-and-test
      develop:
        - step: *Build-and-test
