version: '3.9'

services:
  communication-server:
    image: game/communication-server
    build:
      context: .
      dockerfile: CommunicationServer/Dockerfile
    ports:
      -  "44360:44360"
      -  "44370:44370"


  game-master:
    image: game/game-master
    build:
      context: .
      dockerfile: GameMaster/Dockerfile
    ports:
      -  "5000:80"
      -  "44370:44370"
